set windows-shell := ["C:/Program Files/Git/bin/bash.exe", "-c"]

# Auto-load `.env` (gitignored) for per-developer overrides such as BLENDER
# and BLENDER_MCP_ADDON.
# Existing shell environment variables take precedence (dotenv-override = false).
set dotenv-load := true

# Blender executable. Override with `BLENDER=/path/to/blender just build`
# or via `.env`. CI sets this from the setup-blender action.
export BLENDER := env_var_or_default("BLENDER", "blender")

# Extension source root: the directory holding blender_manifest.toml.
src_dir := "src/silicone_molding"

# Pinned to the *minimum* supported Blender API (5.1) so that 5.2-only
# additions are caught at type-check time rather than by a user on 5.1.
stubs := "fake-bpy-module-5.1"

# Default recipe (shows help)
default:
    @just --list

# Show help
help:
    @just --list

# Setup the development environment
setup:
    uv venv --clear
    uv sync
    uv run pre-commit install

# Run pre-commit hooks (ruff fix + format, mdformat, codespell, ...)
format:
    uv run pre-commit run -a

# Run pytest against the PyPI `bpy` wheel (tier 1)
test:
    uv run pytest -v --cov

# fake-bpy-module and the real bpy wheel both own the `bpy` package name, so
# they must never share an environment -- hence the throwaway env.
[doc("Run pyright strict over src/ in an isolated env")]
type:
    uv run --isolated --with {{stubs}} --with pyright pyright {{src_dir}}

# Run all workflow (format, test, type)
run: format test type

# Validate the extension manifest
validate:
    "$BLENDER" --command extension validate {{src_dir}}

# Build the distributable extension zip into dist/
build: validate
    mkdir -p dist
    "$BLENDER" --command extension build --source-dir {{src_dir}} --output-dir dist

# Build and install the extension into the real Blender, enabled
install: build
    "$BLENDER" --command extension install-file --repo user_default --enable dist/silicone_molding-$(just version).zip

# Requires a real Blender install, unlike `just test`.
[doc("Install, then run the tier-2 integration checks in a real Blender")]
blender-test: install
    "$BLENDER" --background --python tests/blender/run.py

# For trying the add-on by hand. Blender does not reload extension modules in
# place, so re-run this after every code change. The BlenderMCP server is
# started too, so Claude can inspect the same session while you work.
# This blocks until Blender exits.
[doc("Launch Blender with the add-on loaded, plus the MCP server")]
dev: install
    "$BLENDER" --python tools/launch_dev.py

# `--no-project` keeps this off the dev env so the release workflow does not
# have to download the 380MB bpy wheel just to read one field.
[doc("Print the version from blender_manifest.toml (single source of truth)")]
version:
    @uv run --no-project python -c "import tomllib,pathlib;print(tomllib.loads(pathlib.Path('{{src_dir}}/blender_manifest.toml').read_text())['version'])"

# Regenerate the golden meshes under tests/fixtures/
fixtures:
    PYTHONPATH=src uv run python tests/generate_fixtures.py

# Clean autogenerated files
clean:
    rm -rf dist
    find . -type f -name "*.DS_Store" -ls -delete
    find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
    find . | grep -E ".pytest_cache" | xargs rm -rf
    rm -f .coverage
