"""Shared test helpers: mesh invariants and golden-mesh comparison.

Golden meshes are stored as plain-text Wavefront OBJ under
``tests/fixtures/`` so that diffs are readable in review. The reader and
writer here are deliberately minimal and hand-rolled rather than going
through ``bpy.ops.wm.obj_export``: the operator needs a window-manager
context and its output formatting drifts between Blender releases, both
of which would make the fixtures unstable.
"""

from dataclasses import dataclass
from pathlib import Path

# The PyPI `bpy` wheel registers `bmesh` and `mathutils` as builtin modules
# from inside bpy's own C initialiser, so a bare `import bmesh` raises
# ModuleNotFoundError in a fresh interpreter. Inside Blender they are always
# present. isort would otherwise sort `bmesh` ahead of `bpy` and break the
# tier-1 suite, so this module owns the only `import bmesh` under tests/ and
# everything else goes through the helpers below.
# isort: off
import bpy
import bmesh

# isort: on

FIXTURES_DIR = Path(__file__).parent / "fixtures"

#: Digits written to (and compared at) in the OBJ fixtures.
_PRECISION = 6

Vertex = tuple[float, float, float]
Face = tuple[int, ...]


@dataclass(frozen=True)
class MeshData:
    """Positions and face indices of a mesh, detached from Blender."""

    vertices: tuple[Vertex, ...]
    faces: tuple[Face, ...]


@dataclass(frozen=True)
class MeshInvariants:
    """Topological and metric properties that survive re-indexing.

    These are asserted independently of the golden fixture so that a
    test still states *what* the geometry should be, not merely that it
    did not change.
    """

    vertex_count: int
    edge_count: int
    face_count: int
    boundary_edge_count: int
    non_manifold_edge_count: int
    loose_part_count: int
    volume: float
    bbox_min: Vertex
    bbox_max: Vertex

    @property
    def is_watertight(self) -> bool:
        """True when every edge is shared by exactly two faces."""
        return self.boundary_edge_count == 0 and self.non_manifold_edge_count == 0


def make_cube_mesh(size: float, name: str) -> bpy.types.Mesh:
    """Create a closed axis-aligned cube mesh datablock of edge *size*."""
    bm = bmesh.new()
    try:
        bmesh.ops.create_cube(bm, size=size)
        mesh = bpy.data.meshes.new(name)
        bm.to_mesh(mesh)
    finally:
        bm.free()
    return mesh


def mesh_data(mesh: bpy.types.Mesh) -> MeshData:
    """Extract positions and face indices from *mesh*."""
    vertices = tuple(
        (float(v.co.x), float(v.co.y), float(v.co.z)) for v in mesh.vertices
    )
    faces = tuple(tuple(p.vertices) for p in mesh.polygons)
    return MeshData(vertices=vertices, faces=faces)


def mesh_invariants(mesh: bpy.types.Mesh) -> MeshInvariants:
    """Compute the invariants of *mesh* via bmesh."""
    bm = bmesh.new()
    try:
        bm.from_mesh(mesh)
        boundary = sum(1 for e in bm.edges if len(e.link_faces) < 2)
        non_manifold = sum(1 for e in bm.edges if len(e.link_faces) > 2)
        coords = [v.co for v in bm.verts]
        return MeshInvariants(
            vertex_count=len(bm.verts),
            edge_count=len(bm.edges),
            face_count=len(bm.faces),
            boundary_edge_count=boundary,
            non_manifold_edge_count=non_manifold,
            loose_part_count=_count_loose_parts(bm),
            volume=bm.calc_volume(),
            bbox_min=tuple(min(c[axis] for c in coords) for axis in range(3)),  # type: ignore[return-value]
            bbox_max=tuple(max(c[axis] for c in coords) for axis in range(3)),  # type: ignore[return-value]
        )
    finally:
        bm.free()


def _count_loose_parts(bm: bmesh.types.BMesh) -> int:
    """Count connected components of *bm* by flood-filling across edges."""
    seen: set[int] = set()
    parts = 0
    bm.verts.ensure_lookup_table()
    for start in bm.verts:
        if start.index in seen:
            continue
        parts += 1
        stack = [start]
        while stack:
            vert = stack.pop()
            if vert.index in seen:
                continue
            seen.add(vert.index)
            for edge in vert.link_edges:
                other = edge.other_vert(vert)
                if other is not None and other.index not in seen:
                    stack.append(other)
    return parts


def write_obj(path: Path, data: MeshData) -> None:
    """Write *data* to *path* as Wavefront OBJ with 1-based face indices."""
    lines = ["# generated by tests/generate_fixtures.py -- do not edit by hand"]
    lines += [
        f"v {x:.{_PRECISION}f} {y:.{_PRECISION}f} {z:.{_PRECISION}f}"
        for x, y, z in data.vertices
    ]
    lines += ["f " + " ".join(str(i + 1) for i in face) for face in data.faces]
    path.write_text("\n".join(lines) + "\n")


def read_obj(path: Path) -> MeshData:
    """Read a Wavefront OBJ written by :func:`write_obj`."""
    vertices: list[Vertex] = []
    faces: list[Face] = []
    for line in path.read_text().splitlines():
        if line.startswith("v "):
            x, y, z = (float(part) for part in line.split()[1:4])
            vertices.append((x, y, z))
        elif line.startswith("f "):
            # Only the vertex index is written, so "f 1 2 3" not "f 1/1 2/2".
            faces.append(
                tuple(int(part.split("/")[0]) - 1 for part in line.split()[1:])
            )
    return MeshData(vertices=tuple(vertices), faces=tuple(faces))


def _canonical(data: MeshData) -> tuple[tuple[Vertex, ...], frozenset[tuple[int, ...]]]:
    """Re-express *data* independently of vertex and face ordering.

    Vertices are sorted by rounded position and faces are rewritten as
    sorted tuples of the resulting ranks, so two meshes with the same
    shape compare equal even if built in a different order.
    """
    order = sorted(range(len(data.vertices)), key=lambda i: _rounded(data.vertices[i]))
    rank = {original: new for new, original in enumerate(order)}
    vertices = tuple(data.vertices[i] for i in order)
    faces = frozenset(tuple(sorted(rank[i] for i in face)) for face in data.faces)
    return vertices, faces


def _rounded(vertex: Vertex) -> Vertex:
    return (
        round(vertex[0], _PRECISION),
        round(vertex[1], _PRECISION),
        round(vertex[2], _PRECISION),
    )


def assert_matches_golden(
    mesh: bpy.types.Mesh, golden_name: str, *, tol: float = 10.0**-_PRECISION
) -> None:
    """Assert that *mesh* matches the golden fixture *golden_name*.

    Comparison is order-independent: vertices are matched by canonical
    position order and faces by the set of vertex ranks they connect.
    Regenerate the fixture with ``just fixtures`` when a change to the
    geometry is intended.

    Args:
        mesh: Mesh produced by the code under test.
        golden_name: Name of the fixture file under ``tests/fixtures/``,
            including its ``.obj`` extension.
        tol: Absolute tolerance for each vertex coordinate.
    """
    golden_path = FIXTURES_DIR / golden_name
    assert (
        golden_path.exists()
    ), f"missing golden {golden_path}; run `just fixtures` to create it"

    actual_verts, actual_faces = _canonical(mesh_data(mesh))
    expected_verts, expected_faces = _canonical(read_obj(golden_path))

    assert len(actual_verts) == len(
        expected_verts
    ), f"{golden_name}: vertex count {len(actual_verts)} != {len(expected_verts)}"
    for index, (actual, expected) in enumerate(zip(actual_verts, expected_verts)):
        for axis, (a, e) in enumerate(zip(actual, expected)):
            assert (
                abs(a - e) <= tol
            ), f"{golden_name}: vertex {index} axis {axis}: {a} != {e} (tol {tol})"
    assert actual_faces == expected_faces, f"{golden_name}: face connectivity differs"
